{"name": "Проверка появления ошибки при смене имени пользователя без авторизации", "status": "passed", "start": 1725891340339, "stop": 1725891340623, "uuid": "817ddc0e-5dc0-494a-927f-c7e38d431d98", "historyId": "a99f1ecc12398c4881319543e4c06811", "testCaseId": "a99f1ecc12398c4881319543e4c06811", "fullName": "tests.test_change_user_data.TestChangeUserData#test_change_user_name_without_auth_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_user_data"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "Nightingales-MacBook-Air.local"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_user_data"}]}